spring:
  rabbitmq:
#    host: 192.168.28.127
#    port: 5672
    # 花生壳映射地址
    host: 4996384l2d.goho.co
    port: 41897
    username: itcast
    password: 123321
    virtual-host: /
    listener:
      simple:
        # 每次只能获取一条消息，处理完成才能获取下一个消息
        prefetch: 1